// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo6GSYYrcB0PPE1xH9PJkEnmPVMxY0l2s',
    appId: '1:951777662184:web:4bb60d9c368fcd8920655d',
    messagingSenderId: '951777662184',
    projectId: 'allyfe-webrtc-fa105',
    authDomain: 'allyfe-webrtc-fa105.firebaseapp.com',
    storageBucket: 'allyfe-webrtc-fa105.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR_-aP2pelvOPwAOHWLwmcS0AmgJPiCt0',
    appId: '1:951777662184:android:dda68b75127cd49720655d',
    messagingSenderId: '951777662184',
    projectId: 'allyfe-webrtc-fa105',
    storageBucket: 'allyfe-webrtc-fa105.appspot.com',
  );
}
